import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Container, Box } from "@mui/material";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";

// Component Imports
import Navbar from "@/components/Navbar/Navbar";

import theme from "../theme/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <Navbar />
            <Container maxWidth="xl">
              <main>
                <Box>{children}</Box>
              </main>
            </Container>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
