version: "3.8"

services:
  dataset_analyzer:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      # Mount the backend code to /app for live code updates
      - ./backend:/app
